/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardIcon: typeof import('./src/components/CardIcon.vue')['default']
    CategoryHero: typeof import('./src/components/CategoryHero.vue')['default']
    Index01Hero: typeof import('./src/components/Index01Hero.vue')['default']
    Index02WhoUseUs: typeof import('./src/components/Index02WhoUseUs.vue')['default']
    Index03OurServices: typeof import('./src/components/Index03OurServices.vue')['default']
    Index04WhyChooseUs: typeof import('./src/components/Index04WhyChooseUs.vue')['default']
    Index05Reviews: typeof import('./src/components/Index05Reviews.vue')['default']
    Index06FAQ: typeof import('./src/components/Index06FAQ.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}
